# Generated by Django 5.1.4 on 2024-12-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('trailer', models.URLField()),
                ('director', models.CharField(max_length=255)),
                ('released_date', models.DateField()),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('title', 'released_date')},
            },
        ),
    ]
