# Generated by Django 5.1.4 on 2024-12-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aka', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('featured_in', models.ManyToManyField(related_name='actors', to='movies.movie')),
            ],
        ),
    ]
