# Generated by Django 5.1.4 on 2024-12-26 11:56

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_actor_featured_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
