# Generated by Django 5.1.4 on 2024-12-26 14:11

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    for movie in Movie.objects.all():
        movie.slug = slugify(f"{movie.title} {movie.released_date.year}")
        movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]

