# Generated by Django 5.1.4 on 2024-12-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_comment_slug_like_slug_review_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
