# Generated by Django 5.1.4 on 2024-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
